ALTER TABLE "core"."campaign" ADD COLUMN "coupon_kind" text;--> statement-breakpoint
ALTER TABLE "core"."campaign" ADD COLUMN "coupon_discount_unit" text;--> statement-breakpoint
ALTER TABLE "core"."campaign" ADD COLUMN "coupon_discount_value" numeric(12, 2);--> statement-breakpoint
ALTER TABLE "core"."campaign" ADD COLUMN "coupon_extra_units" integer;--> statement-breakpoint
ALTER TABLE "core"."campaign" ADD COLUMN "coupon_rule" text;--> statement-breakpoint
ALTER TABLE "core"."coupon_redemption" ADD COLUMN "kind_snapshot" text;--> statement-breakpoint
ALTER TABLE "core"."coupon_redemption" ADD COLUMN "product_id" uuid;--> statement-breakpoint
ALTER TABLE "core"."coupon_redemption" ADD COLUMN "units_granted" integer;--> statement-breakpoint
ALTER TABLE "core"."coupon_redemption" ADD COLUMN "balance_after" integer;--> statement-breakpoint
ALTER TABLE "core"."campaign_coupon" ADD COLUMN "kind_snapshot" text;--> statement-breakpoint
ALTER TABLE "core"."campaign_coupon" ADD COLUMN "product_id" uuid;--> statement-breakpoint
ALTER TABLE "core"."campaign_coupon" ADD COLUMN "discount_unit_snapshot" text;--> statement-breakpoint
ALTER TABLE "core"."campaign_coupon" ADD COLUMN "discount_value_snapshot" numeric(12, 2);--> statement-breakpoint
ALTER TABLE "core"."campaign_coupon" ADD COLUMN "currency_code_snapshot" text;--> statement-breakpoint
ALTER TABLE "core"."campaign_coupon" ADD COLUMN "extra_units_snapshot" integer;--> statement-breakpoint
ALTER TABLE "core"."campaign_coupon" ADD COLUMN "rule_snapshot" text;--> statement-breakpoint
-- Spec 0106: minimal backfill so the new NOT NULLs and checks can enter. Every coupon that
-- exists before this migration is a label-only reward = `free_product` (ADR 0098). A
-- product with no coupon was never meaningful and the new check forbids it. Idempotent.
UPDATE "core"."campaign" SET "coupon_kind" = 'free_product' WHERE "coupon_label" IS NOT NULL AND "coupon_kind" IS NULL;--> statement-breakpoint
UPDATE "core"."campaign" SET "coupon_product_id" = NULL WHERE "coupon_label" IS NULL AND "coupon_product_id" IS NOT NULL;--> statement-breakpoint
UPDATE "core"."campaign_coupon" SET "kind_snapshot" = 'free_product' WHERE "kind_snapshot" IS NULL;--> statement-breakpoint
UPDATE "core"."coupon_redemption" SET "kind_snapshot" = 'free_product' WHERE "kind_snapshot" IS NULL;--> statement-breakpoint
ALTER TABLE "core"."campaign_coupon" ALTER COLUMN "kind_snapshot" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "core"."coupon_redemption" ALTER COLUMN "kind_snapshot" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "core"."coupon_redemption" ADD CONSTRAINT "coupon_redemption_product_id_product_id_fk" FOREIGN KEY ("product_id") REFERENCES "core"."product"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "core"."campaign_coupon" ADD CONSTRAINT "campaign_coupon_product_id_product_id_fk" FOREIGN KEY ("product_id") REFERENCES "core"."product"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "core"."campaign" ADD CONSTRAINT "core_campaign_coupon_kind_presence_check" CHECK (("core"."campaign"."coupon_kind" is null) = ("core"."campaign"."coupon_label" is null));--> statement-breakpoint
ALTER TABLE "core"."campaign" ADD CONSTRAINT "core_campaign_reward_kind_check" CHECK ("core"."campaign"."coupon_kind" is null or "core"."campaign"."coupon_kind" in ('free_product', 'two_for_one', 'discount', 'extra_stamps', 'extra_points'));--> statement-breakpoint
ALTER TABLE "core"."campaign" ADD CONSTRAINT "core_campaign_reward_discount_unit_check" CHECK ("core"."campaign"."coupon_discount_unit" is null or "core"."campaign"."coupon_discount_unit" in ('percent', 'amount'));--> statement-breakpoint
ALTER TABLE "core"."campaign" ADD CONSTRAINT "core_campaign_reward_discount_shape_check" CHECK ((coalesce("core"."campaign"."coupon_kind", '') = 'discount') = ("core"."campaign"."coupon_discount_unit" is not null) and ("core"."campaign"."coupon_discount_unit" is null) = ("core"."campaign"."coupon_discount_value" is null));--> statement-breakpoint
ALTER TABLE "core"."campaign" ADD CONSTRAINT "core_campaign_reward_discount_value_check" CHECK ("core"."campaign"."coupon_discount_value" is null or ("core"."campaign"."coupon_discount_unit" = 'percent' and "core"."campaign"."coupon_discount_value" between 1 and 100 and "core"."campaign"."coupon_discount_value" = trunc("core"."campaign"."coupon_discount_value")) or ("core"."campaign"."coupon_discount_unit" = 'amount' and "core"."campaign"."coupon_discount_value" > 0));--> statement-breakpoint
ALTER TABLE "core"."campaign" ADD CONSTRAINT "core_campaign_reward_extra_shape_check" CHECK ((coalesce("core"."campaign"."coupon_kind", '') in ('extra_stamps', 'extra_points')) = ("core"."campaign"."coupon_extra_units" is not null));--> statement-breakpoint
ALTER TABLE "core"."campaign" ADD CONSTRAINT "core_campaign_reward_extra_units_check" CHECK ("core"."campaign"."coupon_extra_units" is null or "core"."campaign"."coupon_extra_units" between 1 and 1000);--> statement-breakpoint
ALTER TABLE "core"."campaign" ADD CONSTRAINT "core_campaign_reward_product_kind_check" CHECK ("core"."campaign"."coupon_product_id" is null or coalesce("core"."campaign"."coupon_kind", '') in ('free_product', 'two_for_one'));--> statement-breakpoint
ALTER TABLE "core"."campaign" ADD CONSTRAINT "core_campaign_reward_rule_check" CHECK ("core"."campaign"."coupon_rule" is null or ("core"."campaign"."coupon_kind" is not null and char_length("core"."campaign"."coupon_rule") between 1 and 2000));--> statement-breakpoint
ALTER TABLE "core"."coupon_redemption" ADD CONSTRAINT "core_coupon_redemption_kind_check" CHECK ("core"."coupon_redemption"."kind_snapshot" in ('free_product', 'two_for_one', 'discount', 'extra_stamps', 'extra_points'));--> statement-breakpoint
ALTER TABLE "core"."coupon_redemption" ADD CONSTRAINT "core_coupon_redemption_product_kind_check" CHECK ("core"."coupon_redemption"."product_id" is null or "core"."coupon_redemption"."kind_snapshot" in ('free_product', 'two_for_one'));--> statement-breakpoint
ALTER TABLE "core"."coupon_redemption" ADD CONSTRAINT "core_coupon_redemption_units_check" CHECK (("core"."coupon_redemption"."units_granted" is not null) = ("core"."coupon_redemption"."kind_snapshot" in ('extra_stamps', 'extra_points')) and ("core"."coupon_redemption"."balance_after" is null) = ("core"."coupon_redemption"."units_granted" is null) and ("core"."coupon_redemption"."units_granted" is null or "core"."coupon_redemption"."units_granted" between 1 and 1000) and ("core"."coupon_redemption"."balance_after" is null or "core"."coupon_redemption"."balance_after" >= 0));--> statement-breakpoint
ALTER TABLE "core"."campaign_coupon" ADD CONSTRAINT "core_campaign_coupon_reward_kind_check" CHECK ("core"."campaign_coupon"."kind_snapshot" is null or "core"."campaign_coupon"."kind_snapshot" in ('free_product', 'two_for_one', 'discount', 'extra_stamps', 'extra_points'));--> statement-breakpoint
ALTER TABLE "core"."campaign_coupon" ADD CONSTRAINT "core_campaign_coupon_reward_discount_unit_check" CHECK ("core"."campaign_coupon"."discount_unit_snapshot" is null or "core"."campaign_coupon"."discount_unit_snapshot" in ('percent', 'amount'));--> statement-breakpoint
ALTER TABLE "core"."campaign_coupon" ADD CONSTRAINT "core_campaign_coupon_reward_discount_shape_check" CHECK ((coalesce("core"."campaign_coupon"."kind_snapshot", '') = 'discount') = ("core"."campaign_coupon"."discount_unit_snapshot" is not null) and ("core"."campaign_coupon"."discount_unit_snapshot" is null) = ("core"."campaign_coupon"."discount_value_snapshot" is null));--> statement-breakpoint
ALTER TABLE "core"."campaign_coupon" ADD CONSTRAINT "core_campaign_coupon_reward_discount_value_check" CHECK ("core"."campaign_coupon"."discount_value_snapshot" is null or ("core"."campaign_coupon"."discount_unit_snapshot" = 'percent' and "core"."campaign_coupon"."discount_value_snapshot" between 1 and 100 and "core"."campaign_coupon"."discount_value_snapshot" = trunc("core"."campaign_coupon"."discount_value_snapshot")) or ("core"."campaign_coupon"."discount_unit_snapshot" = 'amount' and "core"."campaign_coupon"."discount_value_snapshot" > 0));--> statement-breakpoint
ALTER TABLE "core"."campaign_coupon" ADD CONSTRAINT "core_campaign_coupon_reward_extra_shape_check" CHECK ((coalesce("core"."campaign_coupon"."kind_snapshot", '') in ('extra_stamps', 'extra_points')) = ("core"."campaign_coupon"."extra_units_snapshot" is not null));--> statement-breakpoint
ALTER TABLE "core"."campaign_coupon" ADD CONSTRAINT "core_campaign_coupon_reward_extra_units_check" CHECK ("core"."campaign_coupon"."extra_units_snapshot" is null or "core"."campaign_coupon"."extra_units_snapshot" between 1 and 1000);--> statement-breakpoint
ALTER TABLE "core"."campaign_coupon" ADD CONSTRAINT "core_campaign_coupon_reward_product_kind_check" CHECK ("core"."campaign_coupon"."product_id" is null or coalesce("core"."campaign_coupon"."kind_snapshot", '') in ('free_product', 'two_for_one'));--> statement-breakpoint
ALTER TABLE "core"."campaign_coupon" ADD CONSTRAINT "core_campaign_coupon_reward_rule_check" CHECK ("core"."campaign_coupon"."rule_snapshot" is null or ("core"."campaign_coupon"."kind_snapshot" is not null and char_length("core"."campaign_coupon"."rule_snapshot") between 1 and 2000));--> statement-breakpoint
ALTER TABLE "core"."campaign_coupon" ADD CONSTRAINT "core_campaign_coupon_reward_currency_check" CHECK (("core"."campaign_coupon"."currency_code_snapshot" is not null) = (coalesce("core"."campaign_coupon"."discount_unit_snapshot", '') = 'amount') and ("core"."campaign_coupon"."currency_code_snapshot" is null or "core"."campaign_coupon"."currency_code_snapshot" ~ '^[A-Z]{3}$'));