ALTER TABLE "core"."campaign" DROP CONSTRAINT "core_campaign_channel_check";--> statement-breakpoint
ALTER TABLE "core"."campaign" DROP CONSTRAINT "core_campaign_coupon_all_or_nothing_check";--> statement-breakpoint
ALTER TABLE "core"."campaign" DROP CONSTRAINT "core_campaign_coupon_needs_end_check";--> statement-breakpoint
ALTER TABLE "core"."campaign" DROP CONSTRAINT "core_campaign_template_key_check";--> statement-breakpoint
ALTER TABLE "core"."campaign_coupon" DROP CONSTRAINT "core_campaign_coupon_single_origin_check";--> statement-breakpoint
ALTER TABLE "core"."campaign_coupon" ALTER COLUMN "membership_id" DROP NOT NULL;--> statement-breakpoint
ALTER TABLE "core"."campaign" ADD COLUMN "cross_audience" text;--> statement-breakpoint
ALTER TABLE "core"."campaign" ADD COLUMN "cross_valid_days" integer;--> statement-breakpoint
ALTER TABLE "core"."campaign" ADD COLUMN "cross_monthly_cap" integer;--> statement-breakpoint
ALTER TABLE "core"."campaign_coupon" ADD COLUMN "cross_claimed_at" timestamp with time zone;--> statement-breakpoint
CREATE UNIQUE INDEX "core_campaign_coupon_cross_unique" ON "core"."campaign_coupon" USING btree ("campaign_id","consumer_id") WHERE "core"."campaign_coupon"."cross_claimed_at" is not null;--> statement-breakpoint
ALTER TABLE "core"."campaign" ADD CONSTRAINT "core_campaign_cross_shape_check" CHECK ((coalesce("core"."campaign"."template_key", '') = 'cross') = ("core"."campaign"."cross_audience" is not null) and (coalesce("core"."campaign"."template_key", '') = 'cross') = ("core"."campaign"."cross_valid_days" is not null) and (coalesce("core"."campaign"."template_key", '') = 'cross') = ("core"."campaign"."cross_monthly_cap" is not null));--> statement-breakpoint
ALTER TABLE "core"."campaign" ADD CONSTRAINT "core_campaign_cross_audience_check" CHECK ("core"."campaign"."cross_audience" is null or "core"."campaign"."cross_audience" in ('non_members', 'dormant', 'any'));--> statement-breakpoint
ALTER TABLE "core"."campaign" ADD CONSTRAINT "core_campaign_cross_valid_days_check" CHECK ("core"."campaign"."cross_valid_days" is null or "core"."campaign"."cross_valid_days" in (7, 15, 30));--> statement-breakpoint
ALTER TABLE "core"."campaign" ADD CONSTRAINT "core_campaign_cross_monthly_cap_check" CHECK ("core"."campaign"."cross_monthly_cap" is null or "core"."campaign"."cross_monthly_cap" between 1 and 10000);--> statement-breakpoint
ALTER TABLE "core"."campaign" ADD CONSTRAINT "core_campaign_channel_check" CHECK ((coalesce("core"."campaign"."template_key", '') in ('welcome', 'cross')) = (not "core"."campaign"."channel_proximity" and not "core"."campaign"."channel_push"));--> statement-breakpoint
ALTER TABLE "core"."campaign" ADD CONSTRAINT "core_campaign_coupon_all_or_nothing_check" CHECK ((coalesce("core"."campaign"."template_key", '') in ('welcome', 'cross') and "core"."campaign"."coupon_label" is not null and "core"."campaign"."coupon_cost" is not null and "core"."campaign"."coupon_max_redemptions" is null) or (coalesce("core"."campaign"."template_key", '') not in ('welcome', 'cross') and ("core"."campaign"."coupon_label" is null) = ("core"."campaign"."coupon_cost" is null) and ("core"."campaign"."coupon_label" is null) = ("core"."campaign"."coupon_max_redemptions" is null)));--> statement-breakpoint
ALTER TABLE "core"."campaign" ADD CONSTRAINT "core_campaign_coupon_needs_end_check" CHECK (coalesce("core"."campaign"."template_key", '') in ('welcome', 'cross') or "core"."campaign"."coupon_label" is null or "core"."campaign"."ends_at" is not null);--> statement-breakpoint
ALTER TABLE "core"."campaign" ADD CONSTRAINT "core_campaign_template_key_check" CHECK ("core"."campaign"."template_key" is null or "core"."campaign"."template_key" in ('missed_you', 'win_back', 'near_reward', 'unclaimed_reward', 'at_risk', 'welcome', 'cross'));--> statement-breakpoint
ALTER TABLE "core"."campaign_coupon" ADD CONSTRAINT "core_campaign_coupon_membership_check" CHECK ("core"."campaign_coupon"."membership_id" is not null or "core"."campaign_coupon"."cross_claimed_at" is not null);--> statement-breakpoint
ALTER TABLE "core"."campaign_coupon" ADD CONSTRAINT "core_campaign_coupon_single_origin_check" CHECK (num_nonnulls("core"."campaign_coupon"."turn_id", "core"."campaign_coupon"."push_id", "core"."campaign_coupon"."welcome_membership_id", "core"."campaign_coupon"."cross_claimed_at") <= 1);